using System.Collections.Generic;
using System.IO;
using System.Linq;
using EpicGames.Core;
using UnrealBuildTool;

/**
 * The game logic of 5_remake/logic as a module: the same sources, compiled here (nothing is copied). The game uses
 * only its C API (ugh_logic.h, exported from this module). In the editor the module also holds the replay tests:
 * the golden replays checked by 6_verification, run as automation tests (Ugh.Replays).
 */
public class UghLogic : ModuleRules
{
	public UghLogic(ReadOnlyTargetRules Target) : base(Target)
	{
		// the logic includes no engine headers and must not get any: no PCH, no unity (its files have file-local names)
		PCHUsage = PCHUsageMode.NoPCHs;
		bUseUnity = false;
		CppStandard = CppStandardVersion.Cpp20;

		string Remake = Path.GetFullPath(Path.Combine(ModuleDirectory, "..", "..", ".."));
		string Logic = Path.Combine(Remake, "logic");
		string Generated = Path.Combine(ModuleDirectory, "..", "..", "Intermediate", "UghLogicSources");
		PublicIncludePaths.Add(Path.Combine(Logic, "include"));
		PrivateIncludePaths.Add(Path.Combine(Logic, "src"));
		AddSources(Path.Combine(Generated, "Logic"), new Dictionary<string, string> { { "logic", Path.Combine(Logic, "src") } });

		PrivateDependencyModuleNames.Add("Core");
		if (Target.LinkType == TargetLinkType.Modular)
		{
			// the module is a DLL (the editor): the C API is exported here, imported by the game (ugh_logic.h)
			PrivateDefinitions.Add("UGH_LOGIC_EXPORTS=1");
			PublicDefinitions.Add("UGH_LOGIC_IMPORTS=1");
		}

		bool bReplayTests = Target.Type == TargetType.Editor;
		PrivateDefinitions.Add("UGH_REPLAY_TESTS=" + (bReplayTests ? "1" : "0"));
		if (bReplayTests)
		{
			string Verification = Path.GetFullPath(Path.Combine(Remake, "..", "6_verification"));
			PrivateIncludePaths.Add(Logic);          // "testing/TestPilot.hpp"
			PrivateIncludePaths.Add(Verification);   // "check/ReplayCheck.hpp", "replay/...", "keyboard/..."
			AddSources(Path.Combine(Generated, "ReplayTests"), new Dictionary<string, string> {
				{ "testing", Path.Combine(Logic, "testing") },
				{ "check", Path.Combine(Verification, "check") },
				{ "replay", Path.Combine(Verification, "replay") },
				{ "keyboard", Path.Combine(Verification, "keyboard") } });
		}
	}

	/**
	 * Compiles the .cpp files under each root through one file per source in `Folder`, named after its path
	 * (logic_bonuses_Falling.cpp): UBT wants unique file names, and the logic has states of the same name in different
	 * modules (bonuses/Falling.cpp, passengers/standing/Falling.cpp). A file is only rewritten when it changes.
	 */
	private void AddSources(string Folder, Dictionary<string, string> Roots)
	{
		Directory.CreateDirectory(Folder);
		HashSet<string> Wanted = new HashSet<string>();
		foreach (KeyValuePair<string, string> Root in Roots)
		{
			foreach (string Source in Directory.GetFiles(Root.Value, "*.cpp", SearchOption.AllDirectories))
			{
				string Relative = Path.GetRelativePath(Root.Value, Source).Replace('\\', '/');
				string Name = Root.Key + "_" + Relative.Replace('/', '_');
				string Text = "// generated by UghLogic.Build.cs\n#include \"" + Source.Replace('\\', '/') + "\"\n";
				string File = Path.Combine(Folder, Name);
				Wanted.Add(Name);
				if (!System.IO.File.Exists(File) || System.IO.File.ReadAllText(File) != Text)
				{
					System.IO.File.WriteAllText(File, Text);
				}
			}
		}
		foreach (string Stale in Directory.GetFiles(Folder, "*.cpp").Where(f => !Wanted.Contains(Path.GetFileName(f))))
		{
			System.IO.File.Delete(Stale);
		}
		ConditionalAddModuleDirectory(new DirectoryReference(Folder));
	}
}
